### ISSUE TITLE
Logo proposal for Dwarf

### ISSUE THREAD

**Issue by psikoz** [icyleaf/dwarf#3]
Hey @icyleaf 

I want to design a logo for Dwarf. Please let me know what you think.

**Comment by icyleaf** [comment]
@psikoz Very happy to hear that, but this project is stiil in a early stage. I don' t want waste your time and solicitous. May be here is another project is welcome to redesin the icon named [halite](https://github.com/icyleaf/halite). 

No matter the result, thanks.
